Default: &defaults
  user: suiteshare
  password: suiteshare
  host: localhost
  port: 5432
  database: tremps
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: tremps_test
  <<: *defaults

Staging:
  database: tremps_staging
  poolsize: 100
  <<: *defaults

Production:
  database: tremps_production
  poolsize: 100
  <<: *defaults
